# Generated by Django 5.0.7 on 2024-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='represent_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
