# Generated by Django 5.0.7 on 2024-08-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='fieldemployee',
            options={'verbose_name': 'Field Employee', 'verbose_name_plural': 'Field Employees'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskemployee',
            options={'verbose_name': 'Task Employee', 'verbose_name_plural': 'Task Employees'},
        ),
    ]
