# Generated by Django 5.0.7 on 2024-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
