# Generated by Django 5.0.7 on 2024-08-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0002_remove_file_file_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
