# Generated by Django 5.0.7 on 2024-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0003_remove_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='field_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='task_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
