# Generated by Django 5.0.7 on 2024-08-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0004_file_field_id_file_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
