# Generated by Django 5.0.7 on 2024-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_employee_leave_manager_alter_employee_manager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
