# Generated by Django 5.0.7 on 2024-09-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_employee_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leave_manager',
        ),
    ]
