# Generated by Django 5.0.7 on 2024-08-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonise', '0002_alter_field_options_alter_fieldemployee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldemployee',
            name='field',
        ),
        migrations.RemoveField(
            model_name='fieldemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='fieldemployee',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_target_group',
        ),
        migrations.RemoveField(
            model_name='taskemployee',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskemployee',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='FieldEmployee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskEmployee',
        ),
    ]
